CREATE DATABASE [cm7master]
GO
ALTER DATABASE [cm7master] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [cm7master] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [cm7master] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [cm7master] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [cm7master] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [cm7master] SET ARITHABORT OFF 
GO
ALTER DATABASE [cm7master] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [cm7master] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [cm7master] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [cm7master] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [cm7master] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [cm7master] SET CURSOR_DEFAULT GLOBAL
GO
ALTER DATABASE [cm7master] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [cm7master] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [cm7master] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [cm7master] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [cm7master] SET DISABLE_BROKER
GO
ALTER DATABASE [cm7master] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [cm7master] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [cm7master] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [cm7master] SET READ_WRITE
GO
ALTER DATABASE [cm7master] SET RECOVERY FULL 
GO
ALTER DATABASE [cm7master] SET MULTI_USER
GO
ALTER DATABASE [cm7master] SET PAGE_VERIFY CHECKSUM  
GO
USE [cm7master]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [cm7master] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [master]
GO
CREATE LOGIN [cm7master] WITH PASSWORD=N'cm7master', DEFAULT_DATABASE=[cm7master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [cm7master]
GO
CREATE USER [cm7master] FOR LOGIN [cm7master]
GO
USE [cm7master]
GO
ALTER USER [cm7master] WITH DEFAULT_SCHEMA=[cm7master]
GO
USE [cm7master]
GO
EXEC sp_addrolemember N'db_datareader', N'cm7master'
GO
USE [cm7master]
GO
EXEC sp_addrolemember N'db_datawriter', N'cm7master'
GO
USE [cm7master]
GO
EXEC sp_addrolemember N'db_ddladmin', N'cm7master'
GO

USE [cm7master]
GO
CREATE SCHEMA [cm7master] AUTHORIZATION [cm7master]
GO
USE [cm7master]
GO
ALTER USER [cm7master] WITH DEFAULT_SCHEMA=[cm7master]
GO
