CATALINA_PID=@PID_ROOT@/@APPLICATION_NAME@.pid
CATALINA_HOME=@INSTALL_ROOT@/@APPLICATION_PREFIX@-tomcat-installation
CATALINA_OUT=@LOG_ROOT@/@APPLICATION_NAME@.out
CATALINA_TMPDIR=@TMP_ROOT@/@APPLICATION_NAME@
CATALINA_BASE=@APPLICATION_INSTALL_ROOT@
