@ECHO OFF
REM First parameter is the install root
REM Second parameter is the configure root
REM All paramters are optional

SETLOCAL ENABLEEXTENSIONS
IF ERRORLEVEL 1 ECHO Unable to enable extensions

SET MY_DIR=%~dp0
SET INSTALL_ROOT_PARAM=%1
SET CONFIGURE_ROOT_PARAM=%2

IF DEFINED INSTALL_ROOT_PARAM (
  SET APPLICATION_INSTALL_ROOT=%INSTALL_ROOT_PARAM%/@APPLICATION_NAME@
) ELSE (
  SET APPLICATION_INSTALL_ROOT=@APPLICATION_INSTALL_ROOT@
)
SET APPLICATION_INSTALL_ROOT=%APPLICATION_INSTALL_ROOT:/=\%
SET INSTALL_ROOT=%INSTALL_ROOT:/=\%


IF NOT EXIST "%APPLICATION_INSTALL_ROOT%" (
  MD "%APPLICATION_INSTALL_ROOT%"
)

REM First we copy this service to %APPLICATION_INSTALL_ROOT%
ECHO "COPYING FILES..."
XCOPY %MY_DIR%* "%APPLICATION_INSTALL_ROOT%" /E /C /R /I /K /Y /Q

REM Apply configuration
CALL %APPLICATION_INSTALL_ROOT%\INSTALL\postconfigure.bat %CONFIGURE_ROOT_PARAM%

ENDLOCAL
