CREATE ROLE cms LOGIN UNENCRYPTED PASSWORD 'cms' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE mls LOGIN UNENCRYPTED PASSWORD 'mls' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE rls LOGIN UNENCRYPTED PASSWORD 'rls' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;
CREATE ROLE external LOGIN UNENCRYPTED PASSWORD 'external' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;